# HAProxy

# Note : Only minimal memory until development starts
# This is in multi-machine format

Vagrant.configure("2") do |config|
   config.vm.define "haproxy" do |haproxy|
     haproxy.vm.box = "crouchr/rch-centos7"
     haproxy.vm.box_check_update = true

     haproxy.vm.network "public_network", ip: "192.168.1.99", bridge: "wlp3s0"

     haproxy.vm.provider "virtualbox" do |v|
       v.memory = 2048
       v.cpus = 1
     end

     config.vm.provision "shell", path: "setup.sh"

    end
end
