name 'ermin_mariadb'
maintainer 'Richard Crouch'
maintainer_email 'richard.crouch100@gmail.com'
license 'All Rights Reserved'
description 'Installs/Configures ermin-mariadb'
version '0.1.0'
chef_version '>= 18.0'

depends 'ermin_centos7'
depends 'ermin_python3'
