name             'blackrain'
maintainer       'Richard Crouch'
maintainer_email 'richard.crouch100@gmail.com'
license          'Apache-2.0'
description      'Installs/Configures BlackRain2020'
long_description IO.read(File.join(File.dirname(__FILE__), 'README.md'))
version          '0.2.1'
supports         'centos'
chef_version     '>= 14.0'
issues_url       'http://web.ermin/chef-cookbooks/issues'
source_url       'https://github.com/crouchr/learnage/chef-repo'
