name 'ermin-hpot-high-centos7'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'All Rights Reserved'
description 'High Interaction Honeypot'
long_description 'Installs/Configures High Interaction Honeypot on CentOS7'
version '0.1.0'
chef_version '>= 14.0'

depends 'ermin-ppots'
depends 'ermin-snort'