name 'ermin_motd_tradr'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'All Rights Reserved'
description 'Installs/Configures ermin-motd-tradr'
long_description 'Installs/Configures ermin-motd-tradr'
version '0.1.0'
chef_version '>= 18.0'
