# DNS node

# Note : Only minimal memory until development starts
# This is in multi-machine format

Vagrant.configure("2") do |config|
   config.vm.define "dns" do |elk|
     dns.vm.box = "rch-centos7"
     dns.vm.box_check_update = true

     dns.vm.network "public_network", ip: "192.168.1.2", bridge: "enp1s0"

     dns.vm.provider "virtualbox" do |v|
       v.memory = 1024
       v.cpus = 1
     end

     config.vm.provision "shell", path: "setup.sh"

    end
end
