# Backrain development environment
# Note : Only minimal memory until development starts
# This is in multi-machine format

# FIXME : Download from Vagrant Cloud until the box can be stored locally on web.ermin successfully
# Promotions by Jenkins are basically changing the box_version number

Vagrant.configure("2") do |config|
   config.vm.define "br2020" do |br2020|
     #br2020.vm.box = "crouchr/blackrain2020"
     br2020.vm.box = "crouchr/rch-centos7"
     br2020.vm.box_check_update = true
     #br2020.vm.box_url = 'http://web.ermin/boxes/blackrain2020/metadata.json'
     #br2020.vm.box_url = 'https://richardcrouch.s3-eu-west-1.amazonaws.com/boxes/blackrain2020.box'

     br2020.vm.network "public_network", ip: "192.168.1.167", bridge: "virbr1"

     br2020.vm.provider "virtualbox" do |v|
       v.memory = 2048
       v.cpus = 1
     end

    # Enabling the Berkshelf plugin. To enable this globally, add this configuration
    # option to your ~/.vagrant.d/Vagrantfile file
    #br2020.berkshelf.enabled = true
    br2020.vm.provision :chef_solo do |chef|
        chef.arguments = "--chef-license accept"
        chef.add_recipe "blackrain"
    end

end
end
