# Blackrain development environment
# This is in multi-machine format

# FIXME : Download from Vagrant Cloud until the box can be stored locally on web.ermin successfully
# Promotions by Jenkins are basically changing the box_version number

Vagrant.configure("2") do |config|
   config.vm.define "br2020" do |br2020|
       br2020.vm.box = "crouchr/rch-centos7-docker"
       br2020.vm.box_check_update = true
       #br2020.vm.box_url = 'http://web.ermin/boxes/blackrain2020/metadata.json'
       #br2020.vm.box_url = 'https://richardcrouch.s3-eu-west-1.amazonaws.com/boxes/blackrain2020.box'

       br2020.vm.network "public_network", ip: "192.168.1.167", bridge: "virbr1"

       br2020.vm.provider "virtualbox" do |v|
         v.memory = 3090
         v.cpus = 2
       end

       br2020.vm.provision :chef_solo do |chef|
           # Recipes are in chef-repo
           chef.arguments = "--chef-license accept --config /vagrant/learnage/chef-repo/.chef/solo.rb --json-attributes /vagrant/dna.json"
       end

   end
   # NOTE : Synced folders are relative to the directory with the Vagrant file in

   # Mount learnage (the root dir - all other sub-folders can be specified relative to it)
   config.vm.synced_folder '../../../', '/vagrant/learnage', create:true

   # Have the malware collected by Dionaea be visible on my xw6600 dev machine
   config.vm.synced_folder 'malware', '/data/dionaea/binaries'

end
