# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.box = "tradr7"
  config.vm.box_check_update = true
  config.vm.hostname = "iceberg0"

  config.vm.network "forwarded_port", guest: 3000, host: 7000, host_ip: "127.0.0.1"  # Grafana
  config.vm.network "forwarded_port", guest: 80, host: 7080, host_ip: "127.0.0.1"    # Web Front-end
  config.vm.network "forwarded_port", guest: 22, host: 7422, host_ip: "127.0.0.1"    # SSH access

  config.vm.provider "virtualbox" do |vb|
    vb.gui = true
    vb.memory = "2048"
  end

  config.vm.provision "shell", path: "setup.sh"

end
