name 'ermin-mariadb'
maintainer 'Richard Crouch'
maintainer_email 'richard.crouch100@gmail.com'
license 'All Rights Reserved'
description 'Installs/Configures ermin-mariadb'
version '0.1.0'
chef_version '>= 14.0'

depends 'ermin-centos7'
depends 'ermin-python3'
