# Backrain development environment
# Note : Only minimal memory until development starts

# FIXME : Download from Vagrant CLoud until the box can be stored locally opn web.ermin successfully
# Promotions by Jenkins are basically changing the box_version number

Vagrant.configure("2") do |config|
  config.vm.box = "crouchr/blackrain2020"
  config.vm.box_version = "2.0.16"
  config.vm.box_check_update = true
  #config.vm.box_url = 'http://web.ermin/boxes/blackrain2020/metadata.json'
  #config.vm.box_url = 'https://richardcrouch.s3-eu-west-1.amazonaws.com/boxes/blackrain2020.box'

  config.vm.network "public_network", ip: "192.168.1.167", bridge: "virbr1"

  config.vm.provider "virtualbox" do |v|
    v.memory = 3072
    v.cpus = 2
  end

#  config.vm.provision "chef_solo" do |chef|
#    chef.add_recipe "blackrain"
#    chef.arguments = "--chef-license accept"
#  end

end
