# Chef Server
# ===========
# Note : Only minimal memory until development starts
# This is in multi-machine format

Vagrant.configure("2") do |config|
   config.vm.define "chefserver" do |chefserver|
     chefserver.vm.box = "crouchr/rch-centos7"
     chefserver.vm.box_check_update = true

     chefserver.vm.network "public_network", ip: "192.168.1.165", bridge: "br0"

     chefserver.vm.provider "virtualbox" do |v|
       v.memory = 6200
       v.cpus = 2
     end

     config.vm.provision "shell", path: "setup.sh"

    end
end
