# Chef Server
# ===========
# Note : Only minimal memory until development starts
# This is in multi-machine format

Vagrant.configure("2") do |config|
   config.vm.define "chefserver" do |chefserver|
     chefserver.vm.box = "crouchr/rch-centos7"
     chefserver.vm.box_check_update = true

     chefserver.vm.network "public_network", ip: "192.168.1.170", bridge: "wlp3s0"

     # stand-alone Chef needs minimum 8GB RAM
     chefserver.vm.provider "virtualbox" do |v|
       #v.memory = 4096
       v.memory = 8192
       v.cpus = 2
     end

     config.vm.provision "shell", path: "setup.sh"

    end
end
