# Bring up the dockerised honeypots
# $ cd /app/scripts
# $ sudo docker-compose up --no-build
# Static IPs : https://stackoverflow.com/questions/27937185/assign-static-ip-to-docker-container
version: '2.3'

services:
  amun:
    #restart: always
    container_name: amun
    network_mode: "host"
    image: registry:5000/amun:1.0.0
    ports:
      - "135:135"
      - "139:139"
      - "445:445"
    volumes:
      - /data/amun/log:/opt/amun/logs

  glastopf:
    #restart: always
    container_name: glastopf
    network_mode: "host"
    image: registry:5000/glastopf:1.0.0
    ports:
      - "80:80"
    volumes:
      - /data/glastopf/db:/tmp/glastopf/db
      - /data/glastopf/log:/tmp/glastopf/log
