# Docker Registry
# Note : Only minimal memory until development starts
# This is in multi-machine format

Vagrant.configure("2") do |config|
   config.vm.define "registry" do |registry|
     registry.vm.box = "crouchr/rch-centos7"
     registry.vm.box_check_update = true

     registry.vm.network "public_network", ip: "192.168.1.109", bridge: "virbr1"

     registry.vm.provider "virtualbox" do |v|
       v.memory = 1024
       v.cpus = 1
     end

    # Enabling the Berkshelf plugin. To enable this globally, add this configuration
    # option to your ~/.vagrant.d/Vagrantfile file
    #br2020.berkshelf.enabled = true

     config.vm.provision "shell", path: "setup.sh"

    end
end