# Docker Registry
# Note : Only minimal memory until development starts
# This is in multi-machine format

Vagrant.configure("2") do |config|
   config.vm.define "registry" do |registry|
     registry.vm.box = "tradr7"
     registry.vm.box_url = "http://192.168.1.4/boxes/tradr7/tradr7-metadata.json"
     registry.vm.box_check_update = true

     registry.vm.network "public_network", ip: "192.168.1.109", bridge: "eth0"

     registry.vm.provider "virtualbox" do |v|
       v.memory = 1024
       v.cpus = 1
     end

      config.vm.provision "shell", path: "setup.sh"
      config.vm.provision "file", source: "files/motd-registry", destination: "/tmp/etc/motd"
      config.vm.provision "shell", run:  "always", inline: "mv /tmp/etc/motd /etc/motd"
    end
end